import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 p-8 sm:p-12 space-y-6">

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-gray-100 pb-6">
          <div className="w-10 h-10 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center shrink-0">
            <FileText size={24} />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              Terms of Service
            </h1>
            <p className="text-xs text-gray-400">
              Last updated: August 2026
            </p>
          </div>
        </div>

        {/* Content */}
        <div className="space-y-6 text-sm leading-relaxed text-gray-600">

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using DocAI, you agree to be bound by these
              Terms of Service. If you do not agree with any part of these
              terms, you must discontinue use of the application.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              2. Description of Service
            </h2>
            <p>
              DocAI is an AI-powered document analysis platform that allows
              users to upload or connect documents, ask questions, and receive
              AI-generated insights based on selected content.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              3. User Accounts
            </h2>
            <p>
              Users may sign in using Google Authentication. You are responsible
              for maintaining the security of your account and any activities
              performed through it.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              4. Google Drive Integration
            </h2>
            <p>
              If you choose to connect Google Drive, DocAI will access only the
              files and documents that you explicitly select.
            </p>

            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>We do not modify your Google Drive files.</li>
              <li>We do not delete your Google Drive files.</li>
              <li>We only access files necessary to provide requested features.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              5. Acceptable Use
            </h2>

            <p>You agree not to:</p>

            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the service for unlawful purposes.</li>
              <li>Attempt unauthorized access to systems or accounts.</li>
              <li>Upload malicious files, malware, or harmful content.</li>
              <li>Interfere with the operation of the service.</li>
              <li>Violate applicable laws or regulations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              6. Intellectual Property
            </h2>
            <p>
              The DocAI application, branding, software, and related content
              are owned by DocAI or its licensors and are protected by
              applicable intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              7. AI-Generated Content
            </h2>
            <p>
              Responses generated by artificial intelligence may not always be
              accurate, complete, or suitable for every purpose. Users should
              independently verify important information before relying on it.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              8. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, DocAI shall not be liable
              for any indirect, incidental, special, consequential, or punitive
              damages arising from the use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              9. Service Availability
            </h2>
            <p>
              We may modify, suspend, or discontinue any part of the service at
              any time without prior notice. We do not guarantee uninterrupted
              availability of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              10. Privacy
            </h2>
            <p>
              Your use of the service is also governed by our Privacy Policy.
              Please review our Privacy Policy to understand how we collect and
              process information.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              11. Changes to Terms
            </h2>
            <p>
              We may update these Terms of Service from time to time. Updated
              versions will be posted on this page with a revised effective
              date.
            </p>
          </section>

           <section className="space-y-2">
            <h2 className="text-base font-semibold text-gray-900">5. Contact Us</h2>
            <p>
              If you have any questions or concerns regarding this privacy policy or your personal data, please submit your inquiry through our{" "}
              <Link href="/contact" className="text-blue-600 underline font-medium">
                Support & Privacy Request Form
              </Link>.
            </p>
          </section>

        </div>

        {/* Footer */}
        <div className="pt-6 border-t border-gray-100">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm font-medium text-blue-600 hover:text-blue-700 transition"
          >
            <ArrowLeft size={16} />
            Back to Homepage
          </Link>
        </div>

      </div>
    </div>
  );
}

